BenchmarkBible/Models/BibleVerseModel.cs
/* Isaiah Johnson
 * Bible Benchmark
 * April 22, 2018
 * This is my own work.
 */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BenchmarkBible.Models
{
    public class BibleVerseModel
    {
        
        //Instantiate lists used for dropdown in views upon construction
        public BibleVerseModel()
        {
            TestamentList = new SelectList(new[] { "Old Testament", "New Testament" });
            BookList = new SelectList(new[] {"Genesis", "Exodus", "Leviticus", "Numbers", "Deuteronomy", "Joshua", "Judges", "Ruth",
                                                     "1 Samuel", "2 Samuel", "1 Kings", "2 Kings", "1 Chronicles", "2 Chronicles", "Ezra" , "Nehemiah",
                                                     "Esther", "Job", "Psalms", "Proverbs", "Ecclesiastes", "Song of Solomon", "Isaiah", "Jeremiah",
                                                     "Lamentations", "Ezekiel", "Daniel", "Hosea", "Joel", "Amos", "Obadiah", "Jonah", "Micah", "Nahum",
                                                     "Habakkuk", "Zephaniah", "Haggai", "Zechariah", "Malachi", "Matthew", "Mark", "Luke", "John", "Acts", "Romans", "1st Corinthians", "2nd Corinthians", "Galatians",
                                                    "Ephesians", "Philippians", "Colossians", "1st Thessalonians", "2nd Thessalonians", "1st Timothy",
                                                    "2nd Timothy", "Titus", "Philemon", "Hebrews", "James", "1st Peter", "2nd Peter", "1st John", "2nd John",
                                                    "3rd John", "Jude", "Revelation" });
        }

        //Lists to be used in search and insert views
        public IEnumerable<SelectListItem> TestamentList { get; set; }
        public IEnumerable<SelectListItem> BookList { get; set; }

        [Required(ErrorMessage = "Testament Required.")]
        public string Testament { get; set; }

        [Required(ErrorMessage = "Book Required.")]
        public string Book { get; set; }

        [Required(ErrorMessage = "Chapter Required.")]
        public int Chapter { get; set; }

        [DisplayName("Verse Number")]
        [Required(ErrorMessage = "Verse Number Required.")]
        public int VerseNum { get; set; }

        [DisplayName("Verse Text")]
        [Required(ErrorMessage = "Verse Text Required.")]
        public string VerseText { get; set; }

        
    }
}

BenchmarkBible/Controllers/BibleController.cs
/* Isaiah Johnson
 * Bible Benchmark
 * April 22, 2018
 * This is my own work.
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BenchmarkBible.Models;
using BenchmarkBible.Services.Business;

namespace BenchmarkBible.Controllers
{
    public class BibleController : Controller
    {

        //Redirects to InsertView
        public ActionResult GoToInsert()
        {
            BibleVerseModel verseModel = new BibleVerseModel();

            return View("InsertView", verseModel);
        }

        //Redirects to VerseSearch
        public ActionResult GoToSearch()
        {
            BibleVerseModel verseModel = new BibleVerseModel();

            return View("VerseSearch", verseModel);

        }

        [HttpPost]
        public ActionResult addBibleVerse(BibleVerseModel bible)
        {
            BibleService bs = new BibleService();

            //Calls business services' addVerse function
            if (bs.AddVerse(bible))
                return View("InsertSuccess");
            else
                return View("InsertFail");
        }

        public ActionResult SearchBibleVerse(BibleVerseModel bible)
        {
            BibleService bs = new BibleService();
            BibleVerseModel model = bs.FindVerse(bible); //Returns a new model 

            //If a null model is returned, query did not return a result
            if (model != null)
                return View("SearchSuccess", model);
            else
                return View("SearchFailure");
        }
    }
}

BenchmarkBible/Controllers/HomeController.cs
/* Isaiah Johnson
 * Bible Benchmark
 * April 22, 2018
 * This is my own work.
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BenchmarkBible.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View("Index");
        }
    }
}

BenchmarkBible/Views/Bible/InsertFail.cshtml
@{
    ViewBag.Title = "InsertFail";
}

<h2 style="color: #941616">Insert Failed</h2>
<body>
    <br /><br />
    @Html.ActionLink("Back to Search", "GoToSearch", "Bible")
</body>

BenchmarkBible/Views/Bible/InsertSuccess.cshtml
@{
    ViewBag.Title = "InsertSuccess";
}

<h2 style="color: #941616">Insert Successful</h2>

<body>
    <br />
    @Html.ActionLink("Back to Insert", "GoToInsert", "Bible")
    <br />
</body>

BenchmarkBible/Views/Bible/InsertView.cshtml
@model BenchmarkBible.Models.BibleVerseModel

@{
    ViewBag.Title = "InsertView";
}

<h2 style="color: #941616">Insert Verse</h2>


@using (Html.BeginForm("addBibleVerse", "Bible", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4 style="color: #941616">Enter Verse Criteria: </h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Testament, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Testament, Model.TestamentList)
            @Html.ValidationMessageFor(model => model.Testament, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Book, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Book, Model.BookList)
            @Html.ValidationMessageFor(model => model.Book, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Chapter, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Chapter, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Chapter, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.VerseNum, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.VerseNum, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.VerseNum, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.VerseText, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.VerseText, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.VerseText, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
    }

    <div>
        @Html.ActionLink("Back to Home", "Index", "Home")
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

BenchmarkBible/Views/Bible/SearchFailure.cshtml
@{
    ViewBag.Title = "SearchFailure";
}

<h2>Search Failed</h2>

<body>
    <br />
    @Html.ActionLink("Back to Search", "GoToSearch", "Bible")
</body>

BenchmarkBible/Views/Bible/SearchSuccess.cshtml
@model BenchmarkBible.Models.BibleVerseModel

@{
    ViewBag.Title = "SearchSuccess";
}

<h2 style="color: #941616">@Model.Book Chapter @Model.Chapter Verse @Model.VerseNum: @Model.VerseText</h2>

<body>
    <br /> <br />
    @Html.ActionLink("Back to Search", "GoToSearch", "Bible")
</body>

BenchmarkBible/Views/Bible/VerseSearch.cshtml
@model BenchmarkBible.Models.BibleVerseModel

@{
    ViewBag.Title = "Verse Search";
}

<h2 style="color: #941616">Search Verses</h2>

@using (Html.BeginForm("SearchBibleVerse","Bible", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4 style="color: #941616">Enter Search Criteria:</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Testament, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Testament, Model.TestamentList)
            @Html.ValidationMessageFor(model => model.Testament, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Book, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Book, Model.BookList)
            @Html.ValidationMessageFor(model => model.Book, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Chapter, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Chapter, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Chapter, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.VerseNum, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.VerseNum, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.VerseNum, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Search" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to Home", "Index", "Home")
</div>

BenchmarkBible/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2 stlye="color: #941616">Index</h2>

<body>
    @Html.ActionLink("Insert a Verse", "GoToInsert", "Bible")
    <br />
    @Html.ActionLink("Search for a Verse", "GoToSearch", "Bible")
</body>

BenchmarkBible/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container" style="margin-left:0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img src="~/Images/bible.png" class="navbar-img" />
                @Html.ActionLink("BibleDB", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @Html.ActionLink("Search", "GoToSearch", "Bible", new { area = "" } , new { @class = "navbar-brand" })
                    @Html.ActionLink("Insert", "GoToInsert", "Bible", new { area = "" } , new { @class = "navbar-brand" })
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>